// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package hpb

import (
	"math/big"

	"github.com/hpb-project/go-hpb/common"
	"github.com/hpb-project/go-hpb/common/hexutil"
	"github.com/hpb-project/go-hpb/core"
	"github.com/hpb-project/go-hpb/hpb/downloader"
	"github.com/hpb-project/go-hpb/hpb/gasprice"
)

func (c Config) MarshalTOML() (interface{}, error) {
	type Config struct {
		Genesis                 *core.Genesis  `toml:",omitempty"`
		NetworkId               uint64
		SyncMode                downloader.SyncMode
		LightServ               int            `toml:",omitempty"`
		LightPeers              int            `toml:",omitempty"`
		MaxPeers                int            `toml:"-"`
		SkipBcVersionCheck      bool           `toml:"-"`
		DatabaseHandles         int            `toml:"-"`
		DatabaseCache           int
		Hpberbase               common.Address `toml:",omitempty"`
		MinerThreads            int            `toml:",omitempty"`
		ExtraData               hexutil.Bytes  `toml:",omitempty"`
		GasPrice                *big.Int
		EthashCacheDir          string
		EthashCachesInMem       int
		EthashCachesOnDisk      int
		EthashDatasetDir        string
		EthashDatasetsInMem     int
		EthashDatasetsOnDisk    int
		TxPool                  core.TxPoolConfig
		GPO                     gasprice.Config
		EnablePreimageRecording bool
		DocRoot                 string         `toml:"-"`
		PowFake                 bool           `toml:"-"`
		PowTest                 bool           `toml:"-"`
		PowShared               bool           `toml:"-"`
	}
	var enc Config
	enc.Genesis = c.Genesis
	enc.NetworkId = c.NetworkId
	enc.SyncMode = c.SyncMode
	enc.LightServ = c.LightServ
	enc.LightPeers = c.LightPeers
	enc.SkipBcVersionCheck = c.SkipBcVersionCheck
	enc.DatabaseHandles = c.DatabaseHandles
	enc.DatabaseCache = c.DatabaseCache
	enc.Hpberbase = c.Hpberbase
	enc.MinerThreads = c.MinerThreads
	enc.ExtraData = c.ExtraData
	enc.GasPrice = c.GasPrice
	enc.EthashCacheDir = c.HpbhashCacheDir
	enc.EthashCachesInMem = c.HpbhashCachesInMem
	enc.EthashCachesOnDisk = c.HpbhashCachesOnDisk
	enc.EthashDatasetDir = c.HpbhashDatasetDir
	enc.EthashDatasetsInMem = c.HpbhashDatasetsInMem
	enc.EthashDatasetsOnDisk = c.HpbhashDatasetsOnDisk
	enc.TxPool = c.TxPool
	enc.GPO = c.GPO
	enc.EnablePreimageRecording = c.EnablePreimageRecording
	enc.DocRoot = c.DocRoot
	enc.PowFake = c.PowFake
	enc.PowTest = c.PowTest
	enc.PowShared = c.PowShared
	return &enc, nil
}

func (c *Config) UnmarshalTOML(unmarshal func(interface{}) error) error {
	type Config struct {
		Genesis                 *core.Genesis   `toml:",omitempty"`
		NetworkId               *uint64
		SyncMode                *downloader.SyncMode
		LightServ               *int            `toml:",omitempty"`
		LightPeers              *int            `toml:",omitempty"`
		MaxPeers                *int            `toml:"-"`
		SkipBcVersionCheck      *bool           `toml:"-"`
		DatabaseHandles         *int            `toml:"-"`
		DatabaseCache           *int
		Hpberbase               *common.Address `toml:",omitempty"`
		MinerThreads            *int            `toml:",omitempty"`
		ExtraData               hexutil.Bytes   `toml:",omitempty"`
		GasPrice                *big.Int
		HpbhashCacheDir         *string
		HpbhashCachesInMem      *int
		HpbhashCachesOnDisk     *int
		HpbhashDatasetDir       *string
		HpbhashDatasetsInMem    *int
		HpbhashDatasetsOnDisk   *int
		TxPool                  *core.TxPoolConfig
		GPO                     *gasprice.Config
		EnablePreimageRecording *bool
		DocRoot                 *string `toml:"-"`
		PowFake                 *bool   `toml:"-"`
		PowTest                 *bool   `toml:"-"`
		PowShared               *bool   `toml:"-"`
	}
	var dec Config
	if err := unmarshal(&dec); err != nil {
		return err
	}
	if dec.Genesis != nil {
		c.Genesis = dec.Genesis
	}
	if dec.NetworkId != nil {
		c.NetworkId = *dec.NetworkId
	}
	if dec.SyncMode != nil {
		c.SyncMode = *dec.SyncMode
	}
	if dec.LightServ != nil {
		c.LightServ = *dec.LightServ
	}
	if dec.LightPeers != nil {
		c.LightPeers = *dec.LightPeers
	}
	if dec.SkipBcVersionCheck != nil {
		c.SkipBcVersionCheck = *dec.SkipBcVersionCheck
	}
	if dec.DatabaseHandles != nil {
		c.DatabaseHandles = *dec.DatabaseHandles
	}
	if dec.DatabaseCache != nil {
		c.DatabaseCache = *dec.DatabaseCache
	}
	if dec.Hpberbase != nil {
		c.Hpberbase = *dec.Hpberbase
	}
	if dec.MinerThreads != nil {
		c.MinerThreads = *dec.MinerThreads
	}
	if dec.ExtraData != nil {
		c.ExtraData = dec.ExtraData
	}
	if dec.GasPrice != nil {
		c.GasPrice = dec.GasPrice
	}
	if dec.HpbhashCacheDir != nil {
		c.HpbhashCacheDir = *dec.HpbhashCacheDir
	}
	if dec.HpbhashCachesInMem != nil {
		c.HpbhashCachesInMem = *dec.HpbhashCachesInMem
	}
	if dec.HpbhashCachesOnDisk != nil {
		c.HpbhashCachesOnDisk = *dec.HpbhashCachesOnDisk
	}
	if dec.HpbhashDatasetDir != nil {
		c.HpbhashDatasetDir = *dec.HpbhashDatasetDir
	}
	if dec.HpbhashDatasetsInMem != nil {
		c.HpbhashDatasetsInMem = *dec.HpbhashDatasetsInMem
	}
	if dec.HpbhashDatasetsOnDisk != nil {
		c.HpbhashDatasetsOnDisk = *dec.HpbhashDatasetsOnDisk
	}
	if dec.TxPool != nil {
		c.TxPool = *dec.TxPool
	}
	if dec.GPO != nil {
		c.GPO = *dec.GPO
	}
	if dec.EnablePreimageRecording != nil {
		c.EnablePreimageRecording = *dec.EnablePreimageRecording
	}
	if dec.DocRoot != nil {
		c.DocRoot = *dec.DocRoot
	}
	if dec.PowFake != nil {
		c.PowFake = *dec.PowFake
	}
	if dec.PowTest != nil {
		c.PowTest = *dec.PowTest
	}
	if dec.PowShared != nil {
		c.PowShared = *dec.PowShared
	}
	return nil
}
